# TASK #1: DEFINE SINGLE AND MULTI-DIMENSIONAL  NUMPY ARRAYS

In [1]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 

import numpy as np

# Let's define a one-dimensional array 
list_1 = [50, 60, 80, 100, 200, 300, 500, 600]
list_1

[50, 60, 80, 100, 200, 300, 500, 600]

In [2]:
# Let's create a numpy array from the list "my_list"
my_numpy_array = np.array(list_1)
my_numpy_array

array([ 50,  60,  80, 100, 200, 300, 500, 600])

In [3]:
type(my_numpy_array)

numpy.ndarray

In [4]:
# Multi-dimensional (Matrix definition) 
my_matrix = np.array([[2, 5, 8], [7, 3, 6]  ])
my_matrix

array([[2, 5, 8],
       [7, 3, 6]])

MINI CHALLENGE #1: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [5]:
import numpy as np

array_2x4 = np.array([ [3, 7, 9, 3] , [4, 3, 2, 2] ])

print (array_2x4)

[[3 7 9 3]
 [4 3 2 2]]


# TASK #2: LEVERAGE NUMPY BUILT-IN METHODS AND FUNCTIONS 

In [6]:
# "rand()" uniform distribution between 0 and 1
x = np.random.rand(20)
x

array([4.29285101e-01, 6.20359106e-01, 5.26857086e-01, 8.38653276e-04,
       8.59990489e-01, 7.09214608e-01, 5.58238167e-01, 1.29940891e-01,
       7.85038050e-01, 7.82332036e-02, 5.98858465e-01, 1.03174070e-05,
       2.05393242e-01, 5.27634903e-01, 6.83707844e-01, 7.04980553e-01,
       5.10230721e-01, 5.53655060e-01, 2.24631861e-02, 7.18431151e-01])

In [7]:
# you can create a matrix of random number as well
x = np.random.rand(3, 3)
x

array([[0.85223255, 0.11858015, 0.57150577],
       [0.34637102, 0.85239682, 0.21328826],
       [0.66399998, 0.04899122, 0.58476986]])

In [8]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(1, 50)
x

7

In [9]:
# "randint" can be used to generate a certain number of random itegers as follows
x = np.random.randint(1, 100, 15)
x

array([53, 71, 19, 21, 23, 63, 38, 88, 33, 57,  3, 67, 70, 65, 40])

In [10]:
# np.arange creates an evenly spaced values within a given interval
x = np.arange(1, 30)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [11]:
# create a diagonal of ones and zeros everywhere else
x = np.eye(7)
x

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [12]:
# Matrix of ones
x = np.ones((7, 7))
x

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [13]:
# Array of zeros
x = np.zeros(8)
x

array([0., 0., 0., 0., 0., 0., 0., 0.])

MINI CHALLENGE #2:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [ ]:
import numpy as np
x = int(input ('Please enter a positive integer value'))



In [ ]:
x

In [ ]:
x = np.random.randint(1, x, 10)
x


# TASK #3: PERFORM MATHEMATICAL OPERATIONS IN NUMPY

In [ ]:
# np.arange() returns an evenly spaced values within a given interval


In [ ]:
x = np.arange (1, 10)
x

In [ ]:
y = np.arange(1, 10)
y

In [ ]:
# Add 2 numpy arrays together


In [ ]:
sum = x + y
sum

In [ ]:
squared = x ** 2
squared

In [ ]:
sqrt = np.sqrt(squared)
sqrt

In [ ]:
z = np.exp(y)
z

MINI CHALLENGE #3:
- Given the X and Y values below, obtain the distance between them

```
X = [5, 7, 20]
Y = [9, 15, 4]
```

In [ ]:
x = np.array([5, 7, 20])
y = np.array([9, 15, 4])

z = np.sqrt(x**2 + y**2  )
z

# TASK #4: PERFORM ARRAYS SLICING AND INDEXING 

In [ ]:
import numpy as np
my_numpy_array = np.array([3, 5, 6, 2, 8, 10, 20, 50])
my_numpy_array

In [ ]:
# Access specific index from the numpy array
my_numpy_array[-1]

In [ ]:
# Starting from the first index 0 up until and NOT including the last element
my_numpy_array[0:3]

In [ ]:
# Broadcasting, altering several values in a numpy array at once
my_numpy_array[0:4] = 7
my_numpy_array

In [ ]:
# Let's define a two dimensional numpy array
matrix = np.random.randint(1, 10, (4, 4))
matrix

In [ ]:
# Get a row from a mtrix
matrix[-1]

In [ ]:
# Get one element
matrix[0][2]

MINI CHALLENGE #4:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



In [ ]:
import numpy as np
x =  np.array([
     [2, 30, 20, -2, -4],
     [3, 4,  40, -3, -2],
     [-3, 4, -6, 90, 10],
     [25, 45, 34, 22, 12],
     [13, 24, 22, 32, 37]])
x

TypeError: list indices must be integers or slices, not tuple

# TASK #5: PERFORM ELEMENTS SELECTION (CONDITIONAL)

In [ ]:
matrix = np.random.randint(1, 10, (5, 5))
matrix

In [ ]:
new_matrix = matrix[ matrix > 7 ]
new_matrix

In [ ]:
# Obtain odd elements only
new_matrix = matrix[ matrix % 2 == 1 ]
new_matrix

MINI CHALLENGE #5:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [ ]:
import numpy as np
X = np.array = ([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])
X

In [ ]:
X [ X < 0 ] = 0
X [ X % 2 == 1] = -2
X


# TASK #6: UNDERSTAND PANDAS FUNDAMENTALS

In [ ]:
# Pandas is a data manipulation and analysis tool that is built on Numpy.
# Pandas uses a data structure known as DataFrame (think of it as Microsoft excel in Python). 
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows and columns).
# Series Vs. DataFrame? Series is considered a single column of a DataFrame.

In [ ]:
import pandas as pd

In [ ]:
# Let's define a two-dimensional Pandas DataFrame
# Note that you can create a pandas dataframe from a python dictionary

bank_client_df = pd.DataFrame({'Bank Client ID': [111, 222, 333, 444],
                              'Bank Client Name':['Chanel' , 'Steve' , 'Mitch' , 'Ryan'],
                              'Net Worth [$]':[3500, 29000, 10000, 2000],
                              'Years with Bank':[3, 4, 9, 5]})
bank_client_df

In [ ]:
# Let's obtain the data type 
type(bank_client_df)

In [ ]:
# you can only view the first couple of rows using .head()
bank_client_df.head(2)

In [ ]:
# you can only view the last couple of rows using .tail()
bank_client_df.tail(2)

MINI CHALLENGE #6:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [ ]:
import pandas as pd
stock_portfolio_df = pd.DataFrame({'Stock Ticker': ['AMZN', 'GOOG', 'NVDIA'],
                                   'Number of Shares' : [10000, 500000, 100000],
                                   'Price Per Share [$]' : [100, 200, 300]})
stock_portfolio_df

In [ ]:
stock_portfolio_df = stock_portfolio_df['Price Per Share [$]'] * stock_portfolio_df['Number of Shares']
stock_portfolio_df.sum()

# TASK #7: PANDAS WITH CSV AND HTML DATA

In [3]:
# Pandas is used to read a csv file and store data in a DataFrame
import pandas as pd
house_price_df = pd.read_html('https://www.livingin-canada.com/house-prices-canada.html')
house_price_df[0]


URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)>

In [ ]:
# Read tabular data using read_html


In [ ]:
!pip install lxml

In [ ]:
!python -m pip install --upgrade pip

In [3]:
pip install --upgrade certifi

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorboard 2.1.1 requires setuptools>=41.0.0, but you have setuptools 39.0.1 which is incompatible.



   ---------------------------------------- 163.8/163.8 kB 5.0 MB/s eta 0:00:00
  Attempting uninstall: certifi
    Found existing installation: certifi 2019.11.28
    Uninstalling certifi-2019.11.28:
      Successfully uninstalled certifi-2019.11.28


MINI CHALLENGE #7:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html 

In [2]:
retirement_df = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
retirement_df[0]

Year of birth  \
0                                      1937 and prior   
1                                                1938   
2                                                1939   
3                                                1940   
4                                                1941   
5                                                1942   
6                                             1943-54   
7                                                1955   
8                                                1956   
9                                                1957   
10                                               1958   
11                                               1959   
12                                     1960 and later   
13  Notes: 1. Persons born on January 1 of any yea...   

                                                  Age  
0                                                  65  
1                                     65 and 2 months  
2                                     65 and 4 months  
3                                     65 and 6 months  
4                                     65 and 8 months  
5                                    65 and 10 months  
6                                                  66  
7                                     66 and 2 months  
8                                     66 and 4 months  
9                                     66 and 6 months  
10                                    66 and 8 months  
11                                   66 and 10 months  
12                                                 67  
13  Notes: 1. Persons born on January 1 of any yea...

# TASK #8: PANDAS OPERATIONS

In [4]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank Client ID': [111, 222, 333, 444],
                              'Bank Client Name':['Chanel' , 'Steve' , 'Mitch' , 'Ryan'],
                              'Net Worth [$]':[3500, 29000, 10000, 2000],
                              'Years with Bank':[3, 4, 9, 5]})
bank_client_df

Bank Client ID Bank Client Name  Net Worth [$]  Years with Bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [7]:
# Pick certain rows that satisfy a certain criteria 
df_loyal = bank_client_df[  bank_client_df['Years with Bank'] >=5  ]
df_loyal

Bank Client ID Bank Client Name  Net Worth [$]  Years with Bank
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [8]:
# Delete a column from a DataFrame
del bank_client_df['Bank Client ID']
bank_client_df

Bank Client Name  Net Worth [$]  Years with Bank
0           Chanel           3500                3
1            Steve          29000                4
2            Mitch          10000                9
3             Ryan           2000                5

MINI CHALLENGE #8:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [9]:
df_high_networth = bank_client_df[  bank_client_df['Net Worth [$]'] >=5000  ]
df_high_networth

Bank Client Name  Net Worth [$]  Years with Bank
1            Steve          29000                4
2            Mitch          10000                9

In [10]:
df_high_networth['Net Worth [$]'].sum()

39000

# TASK #9: PANDAS WITH FUNCTIONS

In [11]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank Client ID': [111, 222, 333, 444],
                              'Bank Client Name':['Chanel' , 'Steve' , 'Mitch' , 'Ryan'],
                              'Net Worth [$]':[3500, 29000, 10000, 2000],
                              'Years with Bank':[3, 4, 9, 5]})
bank_client_df

Bank Client ID Bank Client Name  Net Worth [$]  Years with Bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [12]:
# Define a function that increases all clients networth (stocks) by a fixed value of 20% (for simplicity sake) 

def networth_update(balance):
    return balance * 1.2


In [14]:
# You can apply a function to the DataFrame 
bank_client_df['Net Worth [$]'].apply(networth_update)

0     4200.0
1    34800.0
2    12000.0
3     2400.0
Name: Net Worth [$], dtype: float64

In [15]:
bank_client_df['Bank Client Name'].apply(len)

0    6
1    5
2    5
3    4
Name: Bank Client Name, dtype: int64

MINI CHALLENGE #9:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [16]:
def networth_update(balance):
    return balance * 3 + 200

In [17]:
results = bank_client_df['Net Worth [$]'].apply(networth_update)
results

0    10700
1    87200
2    30200
3     6200
Name: Net Worth [$], dtype: int64

In [18]:
results.sum()

134300

# TASK #10: PERFORM SORTING AND ORDERING IN PANDAS

In [19]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [20]:
# You can sort the values in the dataframe according to number of years with bank
bank_client_df.sort_values(by = 'Years with bank')

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

In [21]:
# Note that nothing changed in memory! you have to make sure that inplace is set to True
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [22]:
# Set inplace = True to ensure that change has taken place in memory 
bank_client_df.sort_values(by = 'Years with bank' , inplace = True)

In [23]:
# Note that now the change (ordering) took place 
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

# TASK #11: PERFORM CONCATENATING AND MERGING WITH PANDAS

In [ ]:
# Check this out: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html

In [24]:
df1 = pd.DataFrame({ 'A': ['A0', 'A1', 'A2', 'A3'],
                   'B': ['B0', 'B1', 'B2', 'B3'],
                   'C': ['C0', 'C1', 'C2', 'C3'],
                   'D': ['D0', 'D1', 'D2', 'D3']},
                  index = [0, 1, 2, 3])

In [25]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [26]:
df2 = pd.DataFrame({ 'A': ['A4', 'A5', 'A6', 'A7'],
                   'B': ['B4', 'B5', 'B6', 'B7'],
                   'C': ['C4', 'C5', 'C6', 'C7'],
                   'D': ['D4', 'D5', 'D6', 'D7']},
                  index = [4, 5, 6, 7])

In [27]:
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [28]:
df3 = pd.DataFrame({ 'A': ['A8', 'A9', 'A10', 'A11'],
                   'B': ['B8', 'B9', 'B10', 'B11'],
                   'C': ['C8', 'C9', 'C10', 'C11'],
                   'D': ['D8', 'D9', 'D10', 'D11']},
                  index = [8, 9, 10, 11])

In [29]:
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [30]:
pd.concat([df1, df2, df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

# TASK #12: PROJECT AND CONCLUDING REMARKS

- Define a dataframe named 'Bank_df_1' that contains the first and last names for 5 bank clients with IDs = 1, 2, 3, 4, 5 
- Assume that the bank got 5 new clients, define another dataframe named 'Bank_df_2' that contains a new clients with IDs = 6, 7, 8, 9, 10
- Let's assume we obtained additional information (Annual Salary) about all our bank customers (10 customers) 
- Concatenate both 'bank_df_1' and 'bank_df_2' dataframes
- Merge client names and their newly added salary information using the 'Bank Client ID'
- Let's assume that you became a new client to the bank
- Define a new DataFrame that contains your information such as client ID (choose 11), first name, last name, and annual salary.
- Add this new dataframe to the original dataframe 'bank_df_all'.

In [33]:
raw_data = { 'Bank Client ID' : ['1', '2', '3', '4', '5'],
             'First Name':['Victor' , 'Steve' , 'Mitch' , 'Ryan' , 'Bob'],
             'Last Name':['Hargobind' , 'Smith' , 'Marner' , 'Getzlaf', 'Cortes']}

Bank_df_1 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_1


Bank Client ID First Name  Last Name
0              1     Victor  Hargobind
1              2      Steve      Smith
2              3      Mitch     Marner
3              4       Ryan    Getzlaf
4              5        Bob     Cortes

In [34]:
raw_data = { 'Bank Client ID' : ['6', '7', '8', '9', '10'],
             'First Name':['Bill' , 'Vanessa' , 'Charles' , 'Natalie' , 'Barry'],
             'Last Name':['Christian' , 'Cortes' , 'Roberts' , 'Porter', 'Blueberry']}

Bank_df_2 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_2

Bank Client ID First Name  Last Name
0              6       Bill  Christian
1              7    Vanessa     Cortes
2              8    Charles    Roberts
3              9    Natalie     Porter
4             10      Barry  Blueberry

In [39]:
raw_data = { 'Bank Client ID':['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], 
           'Annual Salary [$/year]': [25000, 35000, 45000, 48000, 49000, 32000, 33000, 34000, 23000, 22000]}
bank_df_salary = pd.DataFrame(raw_data, columns =['Bank Client ID', 'Annual Salary [$/year]'])
bank_df_salary

Bank Client ID  Annual Salary [$/year]
0              1                   25000
1              2                   35000
2              3                   45000
3              4                   48000
4              5                   49000
5              6                   32000
6              7                   33000
7              8                   34000
8              9                   23000
9             10                   22000

In [41]:
bank_df_all = pd.concat([Bank_df_1, Bank_df_2])
bank_df_all

Bank Client ID First Name  Last Name
0              1     Victor  Hargobind
1              2      Steve      Smith
2              3      Mitch     Marner
3              4       Ryan    Getzlaf
4              5        Bob     Cortes
0              6       Bill  Christian
1              7    Vanessa     Cortes
2              8    Charles    Roberts
3              9    Natalie     Porter
4             10      Barry  Blueberry

In [42]:
bank_df_all = pd.merge(bank_df_all, bank_df_salary, on = 'Bank Client ID')
bank_df_all

Bank Client ID First Name  Last Name  Annual Salary [$/year]
0              1     Victor  Hargobind                   25000
1              2      Steve      Smith                   35000
2              3      Mitch     Marner                   45000
3              4       Ryan    Getzlaf                   48000
4              5        Bob     Cortes                   49000
5              6       Bill  Christian                   32000
6              7    Vanessa     Cortes                   33000
7              8    Charles    Roberts                   34000
8              9    Natalie     Porter                   23000
9             10      Barry  Blueberry                   22000

In [49]:
new_client = { 'Bank Client ID': ['11'],
             'First Name': ['Matthew'],
             'Last Name' : ['Perry'],
             'Annual Salary [$/year]' : [5000]}

new_client_df = pd.DataFrame(new_client, columns = {'Bank Client ID' , 'First Name' , 'Last Name' , 'Annual Salary [$/year]'})

In [50]:
new_client_df

Bank Client ID Last Name  Annual Salary [$/year] First Name
0             11     Perry                    5000    Matthew

In [51]:
new_df = pd.concat([bank_df_all, new_client_df], axis = 0)
new_df

Bank Client ID First Name  Last Name  Annual Salary [$/year]
0              1     Victor  Hargobind                   25000
1              2      Steve      Smith                   35000
2              3      Mitch     Marner                   45000
3              4       Ryan    Getzlaf                   48000
4              5        Bob     Cortes                   49000
5              6       Bill  Christian                   32000
6              7    Vanessa     Cortes                   33000
7              8    Charles    Roberts                   34000
8              9    Natalie     Porter                   23000
9             10      Barry  Blueberry                   22000
0             11    Matthew      Perry                    5000

# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

MINI CHALLENGE #1 SOLUTION: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [ ]:
x = np.array([[[3, 7, 9, 3] , [4, 3, 2, 2]]])
x

MINI CHALLENGE #2 SOLUTION:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [ ]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 10)
x

MINI CHALLENGE #3 SOLUTION:
- Given the X and Y values below, obtain the distance between them


```
X = [5, 7, 20]
Y = [9, 15, 4]
```




In [ ]:
X = np.array([5, 7, 20])
Y = np.array([9, 15, 4])
Z = np.sqrt(X**2 + Y**2)
Z

MINI CHALLENGE #4 SOLUTION:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```




In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [ ]:
X[4] = 0
X

MINI CHALLENGE #5 SOLUTION:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```

In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X<0] = 0
X[X%2==1] = -2
X

MINI CHALLENGE #6 SOLUTION:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [ ]:
portfolio_df = pd.DataFrame({'stock ticker symbols':['AAPL', 'AMZN', 'T'],
                             'price per share [$]':[3500, 200, 40], 
                             'Number of stocks':[3, 4, 9]})
portfolio_df

In [ ]:
stocks_dollar_value = portfolio_df['price per share [$]'] * portfolio_df['Number of stocks']
print(stocks_dollar_value)
print('Total portfolio value = {}'.format(stocks_dollar_value.sum()))

MINI CHALLENGE #7 SOLUTION:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html 

In [ ]:
# Read tabular data using read_html
retirement_age_df = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
retirement_age_df

MINI CHALLENGE #8 SOLUTION:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [ ]:
df_high_networth = bank_client_df[ (bank_client_df['Net worth [$]'] >= 5000) ]
df_high_networth

In [ ]:
df_high_networth['Net worth [$]'].sum()

MINI CHALLENGE #9 SOLUTION:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [ ]:
def networth_update(balance):
    return balance * 3 + 200 

In [ ]:
# You can apply a function to the DataFrame 
results = bank_client_df['Net worth [$]'].apply(networth_update)
results

In [ ]:
results.sum()

PROJECT SOLUTION:

In [ ]:
# Creating a dataframe from a dictionary
# Let's define a dataframe with a list of bank clients with IDs = 1, 2, 3, 4, 5 

raw_data = {'Bank Client ID': ['1', '2', '3', '4', '5'],
            'First Name': ['Nancy', 'Alex', 'Shep', 'Max', 'Allen'], 
            'Last Name': ['Rob', 'Ali', 'George', 'Mitch', 'Steve']}

Bank_df_1 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_1


# Let's define another dataframe for a separate list of clients (IDs = 6, 7, 8, 9, 10)
raw_data = {
        'Bank Client ID': ['6', '7', '8', '9', '10'],
        'First Name': ['Bill', 'Dina', 'Sarah', 'Heather', 'Holly'], 
        'Last Name': ['Christian', 'Mo', 'Steve', 'Bob', 'Michelle']}
Bank_df_2 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_2


# Let's assume we obtained additional information (Annual Salary) about our bank customers 
# Note that data obtained is for all clients with IDs 1 to 10 
raw_data = {
        'Bank Client ID': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
        'Annual Salary [$/year]': [25000, 35000, 45000, 48000, 49000, 32000, 33000, 34000, 23000, 22000]}
bank_df_salary = pd.DataFrame(raw_data, columns = ['Bank Client ID','Annual Salary [$/year]'])
bank_df_salary


# Let's concatenate both dataframes #1 and #2
# Note that we now have client IDs from 1 to 10
bank_df_all = pd.concat([Bank_df_1, Bank_df_2])
bank_df_all


# Let's merge all data on 'Bank Client ID'
bank_df_all = pd.merge(bank_df_all, bank_df_salary, on = 'Bank Client ID')
bank_df_all


In [ ]:
new_client = {
        'Bank Client ID': ['11'],
        'First Name': ['Ry'], 
        'Last Name': ['Aly'],
        'Annual Salary [$/year]' : [1000]}
new_client_df = pd.DataFrame(new_client, columns = ['Bank Client ID', 'First Name', 'Last Name', 'Annual Salary [$/year]'])
new_client_df

In [ ]:
new_df = pd.concat([bank_df_all, new_client_df], axis = 0)
new_df